name: CI/CD Pipeline for IIS

on:
  push:
    branches: [ main ]

env:
  WEB_SERVER_PATH: 'C:\nginx\html\index'

jobs:
  test-job:
    name: Run automated tests
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute test script
        shell: powershell
        run: ./test.ps1

  deploy-job:
    name: Deploy files to IIS folder
    runs-on: self-hosted
    needs: test-job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to web directory
        shell: powershell
        run: |
          robocopy . C:\Lab1 /MIR /R:1 /W:1 /XD .git .github
          exit 0
          Write-Host "Deployment completed!"